### PR TITLE
Add ESLint and some basic rules

### PR DESCRIPTION
**Pull request by S1SYPHOS**
Simple `gulp-eslint` task, eslintrc file with pretty basic env settings, eslint-recommended settings and Google's style guide config are enabled by default.

### CODE REVIEW

**Comment by ixkaito** [comment]
@S1SYPHOS 

Thanks! Will merge.

By the way, you seem to have a different email address of commits than your GitHub account. That's why your avatar doesn't show on the commits page. Is it OK?

https://github.com/ixkaito/frasco/commits/master

**Comment by S1SYPHOS** [comment]
I changed it, but for now that's okay, I guess

**Comment by S1SYPHOS** [comment]
Those commits now resolve #12 ...

**Comment by ixkaito** [comment]
@S1SYPHOS Many thanks!

**Pull request merged**
